name: app_agenda
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  device_info_plus: ^10.1.1
  http: ^1.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.5
  animated_widgets: ^1.1.0
  auto_size_text: ^3.0.0
  fluent_ui: ^4.7.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  footer: ^0.0.4
  gap: ^3.0.1
  google_fonts: ^6.1.0
  line_icons: ^2.0.3
  syncfusion_flutter_datepicker: ^26.1.42
  scroll_when_needed: ^3.0.1
  flutter_custom_clippers: ^2.1.0
  input_quantity: ^2.1.1
  decimal: ^3.0.2
  brasil_fields: ^1.14.1
  email_validator: ^3.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  regex_router: ^2.0.2
  image_picker: ^1.0.4
  dotted_border: ^2.1.0
  uuid: ^4.2.1
  gcloud: ^0.8.11
  cached_network_image: ^3.3.0
  paginated_listview: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
